apiVersion : apps/v1
kind: Deployment
metadata:
  name: nguyenduyandroidazuredevopsgithubacraksapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nguyenduyandroidazuredevopsgithubacraksapp
  template:
    metadata:
      labels:
        app: nguyenduyandroidazuredevopsgithubacraksapp 
    spec:
      containers:
        - name: nguyenduyandroidazuredevopsgithubacraksapp 
          image: ilearncontainerreg.azurecr.io/aksdevops:8
          ports:
          - containerPort: 80